#this is a sample Image
FROM ubi8/ubi:8.5
MAINTAINER monish-rohan
RUN yum install -y httpd && \
    yum clean all 
RUN echo "HELLO MURALI SIR" > /var/www/html/index.html
EXPOSE 80
CMD ["httpd", "-D", "FOREGROUND"]
